import AppKit
import XCTest
@testable import FocusFlow2

final class DesignLabStoreTests: XCTestCase {
    func testSaveLoadDeleteAndUndoTransitions() throws {
        try DesignLabTestSupport.withTemporaryHome {
            let store = FFDesignLabStore()
            let tokens = FFDesignTokens()

            XCTAssertEqual(store.variants.count, 0)
            XCTAssertNil(store.activeVariantId)
            XCTAssertFalse(store.popUndo(into: tokens))

            store.pushUndo(tokens)
            let tuned = tunedTokens()
            let lockedVariant = makeVariant(name: "Primary", tokens: tuned)
            var lockedCopy = lockedVariant
            lockedCopy.isLocked = true

            store.save(lockedCopy)
            XCTAssertEqual(store.variants.count, 1)
            XCTAssertEqual(store.variants.first?.id, lockedCopy.id)
            XCTAssertTrue(store.variants.first?.isLocked ?? false)

            store.save(lockedCopy)
            XCTAssertEqual(store.variants.count, 1)

            store.setActive(lockedCopy, applying: tokens)
            XCTAssertEqual(store.activeVariantId, lockedCopy.id)
            XCTAssertEqual(tokens, tuned)

            XCTAssertTrue(store.popUndo(into: tokens))
            XCTAssertEqual(tokens, FFDesignTokens())

            let missing = makeVariant(name: "Missing", tokens: FFDesignTokens())
            store.delete(missing)
            XCTAssertEqual(store.variants.count, 1)

            store.delete(lockedCopy)
            XCTAssertEqual(store.variants.count, 0)
            XCTAssertNil(store.activeVariantId)

            store.clearActive()
            XCTAssertNil(store.activeVariantId)
        }
    }

    func testSetActiveAndClearActiveWriteGuardedState() throws {
        try DesignLabTestSupport.withTemporaryHome {
            let store = FFDesignLabStore()
            var tokens = FFDesignTokens()
            tokens.spacing.md = 18
            let variant = makeVariant(name: "Snapshot", tokens: tokens)

            store.save(variant)
            store.setActive(variant, applying: FFDesignTokens())

            let activeIDPath = DesignLabTestSupport.designLabRoot()
                .appendingPathComponent("active-variant-id.txt")

            XCTAssertTrue(FileManager.default.fileExists(atPath: activeIDPath.path))
            XCTAssertEqual(DesignLabTestSupport.readString(activeIDPath)?.trimmingCharacters(in: .whitespacesAndNewlines), variant.id.uuidString)

            store.clearActive()
            XCTAssertFalse(FileManager.default.fileExists(atPath: activeIDPath.path))
        }
    }

    func testSaveAndReloadPreserveLockedStateAndOrdering() throws {
        try DesignLabTestSupport.withTemporaryHome {
            let store = FFDesignLabStore()

            var first = makeVariant(name: "First", tokens: tunedTokens())
            first.isLocked = true
            store.save(first)

            var second = makeVariant(name: "Second", tokens: FFDesignTokens())
            second.isLocked = false
            store.save(second)

            store.loadAll()

            XCTAssertEqual(store.variants.count, 2)
            let lookup = Dictionary(uniqueKeysWithValues: store.variants.map { ($0.name, $0.isLocked) })
            XCTAssertEqual(lookup["First"], true)
            XCTAssertEqual(lookup["Second"], false)
        }
    }

    func testLockAsDefaultCopiesGeneratedSwiftWithoutMutatingTokens() throws {
        try DesignLabTestSupport.withTemporaryHome {
            let store = FFDesignLabStore()
            let tokens = tunedTokens()
            let before = tokens.copy()
            let previousPasteboard = NSPasteboard.general.string(forType: .string)

            store.lockAsDefault(tokens)

            let generatedCode = NSPasteboard.general.string(forType: .string)
            XCTAssertEqual(tokens, before)
            XCTAssertTrue(generatedCode?.contains("Generated by Design Lab") ?? false)
            XCTAssertTrue(generatedCode?.contains("enum FFSpacing") ?? false)
            XCTAssertTrue(generatedCode?.contains("static let md: CGFloat = 20") ?? false)

            NSPasteboard.general.clearContents()
            if let previousPasteboard {
                NSPasteboard.general.setString(previousPasteboard, forType: .string)
            }
        }
    }

    private func makeVariant(name: String, tokens: FFDesignTokens) -> FFDesignVariant {
        FFDesignVariant(name: name, tokens: tokens)
    }

    private func tunedTokens() -> FFDesignTokens {
        let tokens = FFDesignTokens()
        tokens.spacing.xs = 10
        tokens.spacing.md = 20
        tokens.radius.card = 22
        tokens.sizing.iconFrame = 52
        tokens.ring.size = 220
        tokens.ring.strokeWidth = 6
        tokens.ring.timerFontSize = 66
        tokens.typography.bodySize = 14
        tokens.color.panelFillOpacity = 0.08
        tokens.motion.sectionResponse = 0.36
        tokens.layout.barChartHeight = 160
        return tokens
    }
}
